sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t praveshbaloni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true praveshbaloni/docker-react npm run test