version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules # docker run -v /app/node_modules
      - .:/app #  docker run -v $(pwd)/:app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # docker run -v /app/node_modules
      - .:/app #  docker run -v $(pwd)/:app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["npm", "run", "test"]
